# Generated by Django 5.1.4 on 2025-03-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
